[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.34"

[features]
seeds = false
skip-lint = false

[programs.localnet]
umbra_amm = "CPMMQoayoCZGUq4wQRxrPBNrrExU6PLg1eEAXC83KDzv"

[registry]
url = "https://github.com/umbra-fi/umbra-amm"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/amm"]

# [scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://staging-rpc.dev2.eclipsenetwork.xyz"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "Bzsi8fW9x4ahRgC8xNdxrr5NNWm8DBSrQnE322vi1YWH"

[[test.validator.clone]]
address = "F8vHGYNxWoLWrLYJ6HrksGH7V8TQeqZJPeGNiYkfdYhN"
